In [1]:
import numpy as np

In [2]:
#1)Create a matrix of user defined size with random numbers

In [3]:
row = int(input())
col = int(input())
mat = np.random.randint(10,size=(row,col))
mat

3
3


array([[6, 1, 4],
       [9, 3, 3],
       [6, 9, 7]])

In [4]:
#2)identify the maximum,minmum value postions also print maximum , minm values

In [5]:
temp=[13,81,-18,67,70,-19]

In [7]:
maxInd = np.argmax(temp)
maxInd,temp[maxInd]

(4, 100)

In [8]:
minInd = np.argmin(temp)
minInd,temp[minInd]

(5, -19)

In [9]:
#3)identify the even and odd number

In [1]:
n = int(input())
if(n % 2 == 0):
 print("even")
else:
 print("odd")

4
even


In [2]:
#4)identify if the number is prime or not

In [6]:
n = int(input())
if(n == 2):
    print("prime")
elif(n > 2):
    x = 0
    for i in range(2,n//2):
        if(n % i == 0):
            print("not prime")
            x = 1
    if(x == 0):
        print("prime")
else:
    print("not prime")
   

8
not prime


In [ ]:
#5)convert matrix of any size to any size using reshape

In [2]:
arr = np.array([1,2,3,4])

print (arr)

b = arr.reshape(2,2)

print(b)

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:























+